### ISSUE TITLE
Investigate how to implement https://github.com/kivy/buildozer https://github.com/kivy/python-for-android/

### ISSUE THREAD

**Issue by Nottlespike** [Nottlespike/Gemini-Challenge#2]
Initial investigations on how to build the apk out in full. https://github.com/kivy/buildozer https://github.com/kivy/python-for-android/
Ignore the MD parts of the library for now.

**Comment by FailSpy** [comment]
Initial Buildozer deets:
```bash
pip install cython buildozer
mkdir project && cd project
python3 -m buildozer init
# edit the generated buildozer.spec with a new set of names (app, package, org)
buildozer -v android debug # if you don't have SDK tools configured, watch for the y/n agreement prompt on licenses when it goes to DL
```

**Comment by FailSpy** [comment]
@AnObfuscator See if you can get a build environment going and replicate the process above. At that point this first step of investigation is done.

**Comment by AnObfuscator** [comment]
In addition to the requirements listed here: https://buildozer.readthedocs.io/en/latest/installation.html

* Needed to install perl
* The docs say it's compatible with JDK 11, but it actually requires 17.

Otherwise, it worked for me on Fedora, using a Conda env with Python 3.12 and OpenJDK 17.
